### ISSUE TITLE
massenhaft Fehler im LOG

### ISSUE THREAD

**Issue by geigl** [iobroker-community-adapters/ioBroker.wolf-smartset#201]
Ich habe unzähligemal am Tag diese 2 Fehlermeldungn

TypeError: Cannot read properties of undefined (reading 'Values')

 API GET GUI DESK. ERROR: Error: read ECONNRESET

Wie bringe ich dies weg?

**Comment by geigl** [comment]
Connecion is stable

**Comment by Apollon77** [comment]
ECONNRESET means that the device cancelled the cnnectio ... so something is not stable ... did that happen still? Any chance to "restart" the wolf device?

**Comment by geigl** [comment]
It´s the only adapter with connection problems, so my network seems to be stable. The Wolf-device sends data to the portal, I can control all changes on the Webportal immediately. Is it possible to switch off the error messages?

**Comment by dp20eic** [comment]
Hi,

I would like to take on this task, sorry for that.
Today and a few days ago I have these messages in the log, after restarting the adapter I get it working again in most cases, but some time e.g. today, it took longer until it works properly again. At the same time, I was able to connect to "https://www.wolf-smartset.com/" and everything works correctly there.
Looks like a connecting error, something with the token.

ioBroker is actual and I use "beta repository"


Adapter:
Verfügbare Version:            1.0.0
Installierte Version:             1.0.0

_Log_
`

wolf-smartset.0 | 2022-07-26 18:41:58.362 | info | starting. Version 1.0.0 in /opt/iobroker/node_modules/iobroker.wolf-smartset, node: v17.9.0, js-controller: 4.0.23
-- | -- | -- | --
wolf-smartset.0 | 2022-07-26 18:41:58.292 | info | Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
wolf-smartset.0 | 2022-07-26 18:41:26.426 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
wolf-smartset.0 | 2022-07-26 18:41:26.425 | info | terminating
wolf-smartset.0 | 2022-07-26 18:41:26.422 | error | Cannot read properties of undefined (reading 'token_type')
wolf-smartset.0 | 2022-07-26 18:41:26.422 | error | TypeError: Cannot read properties of undefined (reading 'token_type') at WolfSmartSet._generateHeader (/opt/iobroker/node_modules/iobroker.wolf-smartset/lib/wss.js:289:26) at WolfSmartSet._sessionUpdate (/opt/iobroker/node_modules/iobroker.wolf-smartset/lib/wss.js:193:30) at Timeout.<anonymous> (/opt/iobroker/node_modules/iobroker.wolf-smartset/lib/wss.js:44:9) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)
wolf-smartset.0 | 2022-07-26 18:41:26.421 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'token_type')
wolf-smartset.0 | 2022-07-26 18:41:26.420 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
wolf-smartset.0 | 2022-07-26 18:41:13.906 | warn | TypeError: Cannot read properties of undefined (reading 'token_type')
wolf-smartset.0 | 2022-07-26 18:40:58.904 | warn | TypeError: Cannot read properties of undefined (reading 'token_type')
wolf-smartset.0 | 2022-07-26 18:40:52.550 | error | API GET AUTH TOKEN ERROR: Error: Request failed with status code 400
wolf-smartset.0 | 2022-07-26 18:40:52.514 | error | API GET AUTH TOKEN ERROR: Error: Request failed with status code 400
wolf-smartset.0 | 2022-07-26 18:40:51.980 | info | getDeviceList
wolf-smartset.0 | 2022-07-26 18:40:51.970 | info | getDeviceList
wolf-smartset.0 | 2022-07-26 18:40:25.368 | info | starting. Version 1.0.0 in /opt/iobroker/node_modules/iobroker.wolf-smartset, node: v17.9.0, js-controller: 4.0.23
wolf-smartset.0 | 2022-07-26 18:40:25.304 | info | Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
wolf-smartset.0 | 2022-07-26 18:40:20.857 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
wolf-smartset.0 | 2022-07-26 18:40:20.856 | info | terminating
wolf-smartset.0 | 2022-07-26 18:40:20.856 | info | Got terminate signal TERMINATE_YOURSELF
wolf-smartset.0 | 2022-07-26 18:38:32.869 | error | API GET GUI DESK. ERROR: Error: Request failed with status code 400
wolf-smartset.0 | 2022-07-26 18:36:13.522 | error | API GET GUI DESK. ERROR: Error: Request failed with status code 400
wolf-smartset.0 | 2022-07-26 18:33:54.096 | error | API GET GUI DESK. ERROR: Error: Request failed with status code 400
wolf-smartset.0 | 2022-07-26 18:31:34.577 | error | API GET GUI DESK. ERROR: Error: Request failed with status code 400
wolf-smartset.0 | 2022-07-26 18:29:14.370 | error | API GET GUI DESK. ERROR: Error: Request failed with status code 400
wolf-smartset.0 | 2022-07-26 18:26:55.055 | error | API GET GUI DESK. ERROR: Error: Request failed with status code 400
wolf-smartset.0 | 2022-07-26 18:24:35.661 | error | API GET GUI DESK. ERROR: Error: Request failed with status code 400

`

**Comment by Apollon77** [comment]
Plesaseprovide a full debug loglevel log

**Comment by Apollon77** [comment]
No, log, closed
